#!/bin/sh
# Fetch SOEM and generate the one header its CMake build would have produced.
#
# soem_check is an INDEPENDENT master, not a second TwinCAT replay — see the
# comment at the top of soem_check.c. It is kept out of the normal build
# because it needs an external tree; `make soem_check` picks it up once this
# script has run.
set -e
DIR="${SOEM_DIR:-$HOME/soem}"

if [ ! -d "$DIR" ]; then
    echo "Cloning SOEM into $DIR..."
    git clone --depth 1 https://github.com/OpenEtherCATsociety/SOEM.git "$DIR"
fi

# ec_options.h is generated by CMake from ec_options.h.in, substituting the
# defaults declared in CMakeLists.txt. We are not using CMake, so do it here.
# The two MAC values need converting from "01:01:..." into the 3 x uint16
# array form the header expects.
python3 - "$DIR" <<'PY'
import re, sys
d = sys.argv[1]
src = open(f"{d}/CMakeLists.txt").read()
vals = dict(re.findall(r'set\((EC_[A-Z0-9_]+)\s+("[^"]*"|\S+)\s+CACHE', src))
def mac(s):
    b = [int(x, 16) for x in s.split(':')]
    return "{" + ",".join(f"0x{b[i]:02x}{b[i+1]:02x}" for i in (0, 2, 4)) + "}"
vals['EC_PRIMARY_MAC_ARRAY']   = mac(vals['EC_PRIMARY_MAC'].strip('"'))
vals['EC_SECONDARY_MAC_ARRAY'] = mac(vals['EC_SECONDARY_MAC'].strip('"'))
tpl = open(f"{d}/include/soem/ec_options.h.in").read()
missing = []
def sub(m):
    k = m.group(1)
    if k not in vals:
        missing.append(k); return "0"
    return vals[k].strip('"')
out = re.sub(r'@(EC_[A-Z0-9_]+)@', sub, tpl)
if missing:
    raise SystemExit("unresolved options: " + ", ".join(missing))
open(f"{d}/include/soem/ec_options.h", "w").write(out)
print("generated", f"{d}/include/soem/ec_options.h")
PY

echo "SOEM ready at $DIR — now run: make soem_check"
